export const board: string[] = [
  "black-rook-head.png",
  "/black-knight-head.png",
  "black-bishop-head.png",
  "/black-queen-head.png",
  "/black-king-head.png",
  "/black-bishop-head.png",
  "/black-knight-head.png",
  "/black-rook-head.png",
  "/black-pawn-head.png",
  "/black-pawn-head.png",
  "/black-pawn-head.png",
  "/black-pawn-head.png",
  "/black-pawn-head.png",
  "/black-pawn-head.png",
  "/black-pawn-head.png",
  "/black-pawn-head.png",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  "/white-pawn-head.png",
  "/white-pawn-head.png",
  "/white-pawn-head.png",
  "/white-pawn-head.png",
  "/white-pawn-head.png",
  "/white-pawn-head.png",
  "/white-pawn-head.png",
  "/white-pawn-head.png",
  "/white-rook-head.png",
  "/white-knight-head.png",
  "/white-bishop-head.png",
  "/white-king-head.png",
  "/white-queen-head.png",
  "/white-bishop-head.png",
  "/white-knight-head.png",
  "/white-rook-head.png",
];
